# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b5c735a336370f4ff049e5d6443eaaa9560f968c4f2a384feec02cf983791cb58a9c251aaa16cf5aca6d08ee133cce6af8fbfe557e0df1795a092429c234656
  twitter_consumer_key: <%= ENV["CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["CONSUMER_SECRET"] %>

test:
  secret_key_base: 26db1bcadb8140eb0adac6cc10f74f047d2817e663135b6ae790d1da0d6ed2514fbfdace417ff85078e45058a8175cc13fb5b74bdffecccc68cb3ab689dbf237
  twitter_consumer_key: <%= ENV["CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["CONSUMER_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
